[package]
name = "reth-contract"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
ethers = "2.0.14"
serde_json = "1.0.140"
tokio = { version = "1.0", features = ["full", "macros", "rt-multi-thread"] }
